### ISSUE TITLE
Pull from Ballerina Central Fails

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/module-ballerinax-aws.ses#4]
**Description:**
When tried to pull this connector from Ballerina Central, there are issues occur.

**Comment by LakshanSS** [comment]
At the moment, a revamp is happening via https://github.com/ballerina-platform/module-ballerinax-aws.ses/pull/6
This connector will be released to ballerina-central with the SLBeta3 release.

After the connector release, this issue will be fixed.
